name: f
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: i
      run: sudo apt-get update && sudo apt-get install -y nasm
    - name: a
      run: nasm -f bin f.s -o f
    - name: u
      uses: actions/upload-artifact@v4
      with:
        name: f
        path: f
